[package]
name = "beet-up"
version = "0.1.0"
authors = ["George Kaplan <george@georgekaplan.xyz>"]
edition = "2018"

[dependencies]
beet_db = { path = "../db" }
structopt = "0.2.14"
warp = "0.1.12"
pretty_env_logger = "0.3.0"
log = "0.4.6"
serde_derive = "1.0.88"
serde = "1.0.88"
url = "1.7.2"
