version: "3"

services:
  proxy:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./tests/nginx.conf:/etc/nginx/nginx.conf:ro
  server:
    build: .
    volumes:
      - ..:/usr/src
  client:
    build: ./www
    volumes:
      - ..:/usr/src
