[package]
name = "beet-up-www"
version = "0.1.0"
authors = ["George Kaplan <george@georgekaplan.xyz>"]
edition = "2018"
publish = false

[dependencies]
beet_db = { path = "../../db" }
stdweb = "0.4.14"
yew = "0.6"
failure = "0.1.5"
