language: rust
cache: cargo

stages:
  - lint
  - test

before_script: ./ci/prebuild.sh
script: ./ci/build.sh

env:
  matrix:
    - RUST=stable
    - RUST=beta
    - RUST=nightly

matrix:
  include:
    - stage: lint
      before_script: ./ci/prelint.sh
      script: ./ci/lint.sh
  allow_failures:
    - rust: nightly
  fast_finish: true
