language: rust
cache: cargo

stages:
  - lint
  - build

matrix:
  include:
    - stage: lint
      rust: stable
      before_script:
        - rustup component add clippy
        - mkdir -p target/wasm32-unknown-unknown/release
        - touch target/wasm32-unknown-unknown/release/beet-up-www.{js,wasm}
      script: cargo clippy --all --verbose -- -D warnings
    - stage: build
      rust:
        - stable
        - beta
        - nightly
      before_script:
        - which cargo-web || cargo install cargo-web
        - rm -rf target/wasm32-unknown-unknown
      script:
        - cargo web build --release -p beet-up-www
        - cargo build --verbose
        - cargo test --verbose
  allow_failures:
    - rust: nightly
  fast_finish: true
