language: rust
cache: cargo

stages:
  - lint
  - test

matrix:
  include:
    - stage: test
      env:
        - RUST=stable
      before_script: ./ci/prebuild.sh
      script: ./ci/build.sh
    - stage: test
      env:
        - RUST=beta
      before_script: ./ci/prebuild.sh
      script: ./ci/build.sh
    - stage: test
      env:
        - RUST=nightly
      before_script: ./ci/prebuild.sh
      script: ./ci/build.sh
    - stage: lint
      before_script: ./ci/prelint.sh
      script: ./ci/lint.sh
  allow_failures:
    - rust: nightly
  fast_finish: true
