language: rust
rust:
  - stable
  - beta
  - nightly
cache: cargo

stages:
  - lint
  - test

matrix:
  include:
    - stage: lint
      rust: stable
      before_script: ./ci/prelint.sh
      script: ./ci/lint.sh
    - stage: test
      rust:
        - stable
        - beta
        - nightly
      before_script: ./ci/prebuild.sh
      script: ./ci/build.sh
  allow_failures:
    - rust: nightly
  fast_finish: true
