language: rust
rust:
  - stable
  - beta
  - nightly
cache: cargo

&wasm_target: "target/wasm32-unknown-unknown/release"

stages:
  - lint
  - test

before_script: which cargo-web || cargo install cargo-web
script:
  - cargo web build --release -p beet-up-www
  - cargo build --verbose
  - cargo test --verbose

matrix:
  include:
    - stage: lint
      rust: stable
      before_script:
        - rustup component add clippy
        - mkdir -p *wasm_target
        - touch *wasm_target/beet-up-www.{js,wasm}
      script: cargo clippy --all -- -D warnings
  allow_failures:
    - rust: nightly
  fast_finish: true
