language: rust
cache: cargo

stages:
  - lint
  - test

matrix:
  include:
    - stage: lint
      rust: stable
      before_script: rustup component add clippy
      script: cargo clippy -- -D warnings
    - stage: test
      rust:
        - beta
        - nightly
      script:
        - cargo build --verbose --all
        - cargo test --verbose --all
  allow_failures:
    - rust: nightly
  fast_finish: true
