[package]
name = "beet-up"
version = "0.1.0"
authors = ["George Kaplan <george@georgekaplan.xyz>"]
edition = "2018"

[dependencies]
beet_db = { path = "../beet_db" }
structopt = "0.2.14"
warp = "0.1.12"
pretty_env_logger = "0.3.0"
log = "0.4.6"
